export const SET_DIFFICULTY_NORMAL = 'DIFFICULTY_NORMAL';
export const SET_DIFFICULTY_EASY = 'DIFFICULTY_EASY';
export const SET_DIFFICULTY_HARD = 'DIFFICULTY_HARD';
export const RESTART_GAME = 'RESTART_GAME';
